set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR s390x)

SET(CMAKE_C_COMPILER s390x-linux-gnu-gcc)
SET(CMAKE_CXX_COMPILER s390x-linux-gnu-g++)
SET(CMAKE_AR s390x-linux-gnu-gcc-ar)
SET(CMAKE_STRIP s390x-linux-gnu-gcc-strip)
SET(CMAKE_RANLIB s390x-linux-gnu-gcc-ranlib)

#SET(CMAKE_CROSSCOMPILING_EMULATOR qemu-s390x-static)

set(CMAKE_FIND_ROOT_PATH $ENV{TARGET_SYSROOT})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
