SET(CMAKE_C_COMPILER clang)
SET(CMAKE_CXX_COMPILER clang++)

# 11.0 is the first macOS to support arm64
SET(CMAKE_OSX_DEPLOYMENT_TARGET 11.0)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_SYSTEM_PROCESSOR "arm64")
set(CMAKE_SYSTEM_NAME "Darwin")
set(CMAKE_OSX_ARCHITECTURES "arm64")
set(CMAKE_C_COMPILER_ARG1 "-arch arm64")
set(CMAKE_CXX_COMPILER_ARG1 "-arch arm64")