set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR ppc64le)

SET(CMAKE_C_COMPILER powerpc64le-linux-gnu-gcc)
SET(CMAKE_CXX_COMPILER powerpc64le-linux-gnu-g++)
SET(CMAKE_AR powerpc64le-linux-gnu-gcc-ar)
SET(CMAKE_STRIP powerpc64le-linux-gnu-gcc-strip)
SET(CMAKE_RANLIB powerpc64le-linux-gnu-gcc-ranlib)

#SET(CMAKE_CROSSCOMPILING_EMULATOR qemu-ppc64le-static)

set(CMAKE_FIND_ROOT_PATH $ENV{TARGET_SYSROOT})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
