[host_machine]
system = 'linux'
cpu_family = 'loongarch64'
cpu = 'loongarch64'
endian = 'little'

[binaries]
c = 'loongarch64-linux-gnu-gcc-14'
cpp = 'loongarch64-linux-gnu-g++-14'
ar = 'loongarch64-linux-gnu-ar'
nm = 'loongarch64-linux-gnu-nm'
ld = 'loongarch64-linux-gnu-ld'
strip = 'loongarch64-linux-gnu-strip'
ranlib = 'loongarch64-linux-gnu-ranlib'

[properties]
# https://docs.gtk.org/glib/cross-compiling.html#cross-properties
have_c99_vsnprintf = true
have_c99_snprintf = true
have_unix98_printf = true

[built-in options]
libdir = 'lib'
datadir = '/usr/share'
localedir = '/usr/share/locale'
sysconfdir = '/etc'
localstatedir = '/var'
wrap_mode = 'nofallback'
