name: CI
on:
  push:
    branches:
      - main
      - 'temp-*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
permissions: {}
jobs:
  check-latest-versions:
    permissions:
      contents: read
    runs-on: 'ubuntu-26.04'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: ./check-latest-versions.sh && git diff --quiet
  build:
    permissions:
      contents: read
    name: build-${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    needs: check-latest-versions
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 'ubuntu-26.04'
            platform: 'linux-x64'
          - os: 'ubuntu-26.04'
            platform: 'linux-armv6'
          - os: 'ubuntu-26.04'
            platform: 'linuxmusl-x64'
          - os: 'ubuntu-26.04'
            platform: 'linux-ppc64le'
          - os: 'ubuntu-26.04'
            platform: 'linux-riscv64'
          - os: 'ubuntu-26.04'
            platform: 'linux-s390x'
          - os: 'ubuntu-26.04'
            platform: 'dev-wasm32'
          - os: 'ubuntu-26.04'
            platform: 'win32-ia32'
          - os: 'ubuntu-26.04'
            platform: 'win32-x64'
          - os: 'ubuntu-26.04'
            platform: 'win32-arm64v8'
          - os: 'macos-15-intel'
            platform: 'darwin-x64'
          - os: 'macos-15'
            platform: 'darwin-arm64v8'
          - os: 'ubuntu-26.04-arm'
            platform: 'linux-arm64v8'
          - os: 'ubuntu-26.04-arm'
            platform: 'linuxmusl-arm64v8'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          pipx install meson
          brew install automake nasm
      - name: Build ${{ matrix.platform }}
        run: ./build.sh ${{ matrix.platform }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: build-${{ matrix.platform }}
          path: '*.tar.gz'
          compression-level: 0
          retention-days: 1
          if-no-files-found: error
  populate-and-publish-npm-workspace:
    permissions:
      contents: write
      id-token: write
    needs: build
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24'
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          merge-multiple: true
      - name: Populate npm workspace
        run: ./populate-npm-workspace.sh
      - name: Create npm workspace tarball
        run: tar -vcaf npm-workspace.tar.xz -C npm .
      - name: Generate release notes
        run: ./generate-release-notes.sh
      - name: Create GitHub release for tag
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          artifacts: npm-workspace.tar.xz
          artifactContentType: application/x-xz
          bodyFile: release-notes.md
          prerelease: ${{ contains(github.ref, '-rc') }}
          makeLatest: ${{ !contains(github.ref, '-rc') }}
      - name: Publish npm packages
        if: startsWith(github.ref, 'refs/tags/v')
        run: cd npm && npm publish --workspaces --tag=${{ contains(github.ref, '-rc') && 'next' || 'latest' }}
